### ISSUE TITLE
reddemNitro

### ISSUE THREAD

**Issue by aiko-chan-ai** [Danspotnytool/nitro-sniper#1]
I wanted to let you know that the reddemNitro method will be changed in an upcoming update of the module
Changed to redeemNitro
If you plan to update the module, that's also something to keep in mind
And the regex to check for nitro I used is
```js
/discord(?:(?:app)?\.com\/gifts|\.gift)\/([\w-]{2,255})/gi
```
Thank you for reading, from the owner of this module: aiko-chan-ai

**Comment by danieljohnbyns** [comment]
Thank you so much for letting me know about this change. Also, thanks for the regex, I'll try that
